version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: backend-postgres-1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: casefolio_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:6
    container_name: backend-redis-1
    ports:
      - '6379:6379'
volumes:
  postgres_data: